# Generated by Django 5.0.2 on 2024-02-09 11:34

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('avto', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Option',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('create_at', models.DateTimeField(auto_now_add=True)),
                ('update_at', models.DateTimeField(auto_now=True)),
                ('title', models.CharField(max_length=256)),
                ('type', models.CharField(choices=[('Single', 'Single'), ('Extended', 'Extended'), ('Choice', 'Choice'), ('Button', 'Button'), ('Text', 'Text'), ('Number', 'Number'), ('Multiple choice', 'Multiple Choice')], max_length=15)),
                ('is_main', models.BooleanField(default=False)),
                ('is_filter', models.BooleanField(default=False)),
                ('is_main_filter', models.BooleanField(default=False)),
                ('is_advanced_filter', models.BooleanField(default=False)),
                ('order', models.IntegerField(default=0)),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='OptionValue',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('create_at', models.DateTimeField(auto_now_add=True)),
                ('update_at', models.DateTimeField(auto_now=True)),
                ('value', models.CharField(max_length=256)),
                ('option', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='values', to='option.option')),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='OptionValueExtended',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('create_at', models.DateTimeField(auto_now_add=True)),
                ('update_at', models.DateTimeField(auto_now=True)),
                ('value', models.CharField(max_length=256)),
                ('option_value', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='values_extended', to='option.optionvalue')),
                ('parent', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='children', to='option.optionvalueextended')),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='PostOption',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('create_at', models.DateTimeField(auto_now_add=True)),
                ('update_at', models.DateTimeField(auto_now=True)),
                ('value', models.CharField(blank=True, max_length=256, null=True)),
                ('option', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='posts', to='option.option')),
                ('post', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='options', to='avto.post')),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='PostOptionValue',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('create_at', models.DateTimeField(auto_now_add=True)),
                ('update_at', models.DateTimeField(auto_now=True)),
                ('option_value', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='option.optionvalue')),
                ('post_option', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='values', to='option.postoption')),
            ],
            options={
                'unique_together': {('post_option', 'option_value')},
            },
        ),
    ]
